apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    name: metallb-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik-system
  labels:
    name: traefik-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
  labels:
    name: cattle-system